// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bep.proto

package bep

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_CLUSTER_CONFIG    MessageType = 0
	MessageType_INDEX             MessageType = 1
	MessageType_INDEX_UPDATE      MessageType = 2
	MessageType_REQUEST           MessageType = 3
	MessageType_RESPONSE          MessageType = 4
	MessageType_DOWNLOAD_PROGRESS MessageType = 5
	MessageType_PING              MessageType = 6
	MessageType_CLOSE             MessageType = 7
)

var MessageType_name = map[int32]string{
	0: "CLUSTER_CONFIG",
	1: "INDEX",
	2: "INDEX_UPDATE",
	3: "REQUEST",
	4: "RESPONSE",
	5: "DOWNLOAD_PROGRESS",
	6: "PING",
	7: "CLOSE",
}

var MessageType_value = map[string]int32{
	"CLUSTER_CONFIG":    0,
	"INDEX":             1,
	"INDEX_UPDATE":      2,
	"REQUEST":           3,
	"RESPONSE":          4,
	"DOWNLOAD_PROGRESS": 5,
	"PING":              6,
	"CLOSE":             7,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{0}
}

type MessageCompression int32

const (
	MessageCompression_NONE MessageCompression = 0
	MessageCompression_LZ4  MessageCompression = 1
)

var MessageCompression_name = map[int32]string{
	0: "NONE",
	1: "LZ4",
}

var MessageCompression_value = map[string]int32{
	"NONE": 0,
	"LZ4":  1,
}

func (x MessageCompression) String() string {
	return proto.EnumName(MessageCompression_name, int32(x))
}

func (MessageCompression) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{1}
}

type Compression int32

const (
	Compression_METADATA Compression = 0
	Compression_NEVER    Compression = 1
	Compression_ALWAYS   Compression = 2
)

var Compression_name = map[int32]string{
	0: "METADATA",
	1: "NEVER",
	2: "ALWAYS",
}

var Compression_value = map[string]int32{
	"METADATA": 0,
	"NEVER":    1,
	"ALWAYS":   2,
}

func (x Compression) String() string {
	return proto.EnumName(Compression_name, int32(x))
}

func (Compression) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{2}
}

type FileInfoType int32

const (
	FileInfoType_FILE              FileInfoType = 0
	FileInfoType_DIRECTORY         FileInfoType = 1
	FileInfoType_SYMLINK_FILE      FileInfoType = 2 // Deprecated: Do not use.
	FileInfoType_SYMLINK_DIRECTORY FileInfoType = 3 // Deprecated: Do not use.
	FileInfoType_SYMLINK           FileInfoType = 4
)

var FileInfoType_name = map[int32]string{
	0: "FILE",
	1: "DIRECTORY",
	2: "SYMLINK_FILE",
	3: "SYMLINK_DIRECTORY",
	4: "SYMLINK",
}

var FileInfoType_value = map[string]int32{
	"FILE":              0,
	"DIRECTORY":         1,
	"SYMLINK_FILE":      2,
	"SYMLINK_DIRECTORY": 3,
	"SYMLINK":           4,
}

func (x FileInfoType) String() string {
	return proto.EnumName(FileInfoType_name, int32(x))
}

func (FileInfoType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{3}
}

type ErrorCode int32

const (
	ErrorCode_NO_ERROR     ErrorCode = 0
	ErrorCode_GENERIC      ErrorCode = 1
	ErrorCode_NO_SUCH_FILE ErrorCode = 2
	ErrorCode_INVALID_FILE ErrorCode = 3
)

var ErrorCode_name = map[int32]string{
	0: "NO_ERROR",
	1: "GENERIC",
	2: "NO_SUCH_FILE",
	3: "INVALID_FILE",
}

var ErrorCode_value = map[string]int32{
	"NO_ERROR":     0,
	"GENERIC":      1,
	"NO_SUCH_FILE": 2,
	"INVALID_FILE": 3,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{4}
}

type FileDownloadProgressUpdateType int32

const (
	FileDownloadProgressUpdateType_APPEND FileDownloadProgressUpdateType = 0
	FileDownloadProgressUpdateType_FORGET FileDownloadProgressUpdateType = 1
)

var FileDownloadProgressUpdateType_name = map[int32]string{
	0: "APPEND",
	1: "FORGET",
}

var FileDownloadProgressUpdateType_value = map[string]int32{
	"APPEND": 0,
	"FORGET": 1,
}

func (x FileDownloadProgressUpdateType) String() string {
	return proto.EnumName(FileDownloadProgressUpdateType_name, int32(x))
}

func (FileDownloadProgressUpdateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{5}
}

type Hello struct {
	DeviceName           string   `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	ClientName           string   `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientVersion        string   `protobuf:"bytes,3,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hello) Reset()         { *m = Hello{} }
func (m *Hello) String() string { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()    {}
func (*Hello) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{0}
}

func (m *Hello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hello.Unmarshal(m, b)
}
func (m *Hello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hello.Marshal(b, m, deterministic)
}
func (m *Hello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hello.Merge(m, src)
}
func (m *Hello) XXX_Size() int {
	return xxx_messageInfo_Hello.Size(m)
}
func (m *Hello) XXX_DiscardUnknown() {
	xxx_messageInfo_Hello.DiscardUnknown(m)
}

var xxx_messageInfo_Hello proto.InternalMessageInfo

func (m *Hello) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *Hello) GetClientName() string {
	if m != nil {
		return m.ClientName
	}
	return ""
}

func (m *Hello) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

type Header struct {
	Type                 MessageType        `protobuf:"varint,1,opt,name=type,proto3,enum=bep.MessageType" json:"type,omitempty"`
	Compression          MessageCompression `protobuf:"varint,2,opt,name=compression,proto3,enum=bep.MessageCompression" json:"compression,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{1}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_CLUSTER_CONFIG
}

func (m *Header) GetCompression() MessageCompression {
	if m != nil {
		return m.Compression
	}
	return MessageCompression_NONE
}

type ClusterConfig struct {
	Folders              []*Folder `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ClusterConfig) Reset()         { *m = ClusterConfig{} }
func (m *ClusterConfig) String() string { return proto.CompactTextString(m) }
func (*ClusterConfig) ProtoMessage()    {}
func (*ClusterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{2}
}

func (m *ClusterConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterConfig.Unmarshal(m, b)
}
func (m *ClusterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterConfig.Marshal(b, m, deterministic)
}
func (m *ClusterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterConfig.Merge(m, src)
}
func (m *ClusterConfig) XXX_Size() int {
	return xxx_messageInfo_ClusterConfig.Size(m)
}
func (m *ClusterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterConfig proto.InternalMessageInfo

func (m *ClusterConfig) GetFolders() []*Folder {
	if m != nil {
		return m.Folders
	}
	return nil
}

type Folder struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label                string    `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	ReadOnly             bool      `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	IgnorePermissions    bool      `protobuf:"varint,4,opt,name=ignore_permissions,json=ignorePermissions,proto3" json:"ignore_permissions,omitempty"`
	IgnoreDelete         bool      `protobuf:"varint,5,opt,name=ignore_delete,json=ignoreDelete,proto3" json:"ignore_delete,omitempty"`
	DisableTempIndexes   bool      `protobuf:"varint,6,opt,name=disable_temp_indexes,json=disableTempIndexes,proto3" json:"disable_temp_indexes,omitempty"`
	Paused               bool      `protobuf:"varint,7,opt,name=paused,proto3" json:"paused,omitempty"`
	Devices              []*Device `protobuf:"bytes,16,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Folder) Reset()         { *m = Folder{} }
func (m *Folder) String() string { return proto.CompactTextString(m) }
func (*Folder) ProtoMessage()    {}
func (*Folder) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{3}
}

func (m *Folder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Folder.Unmarshal(m, b)
}
func (m *Folder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Folder.Marshal(b, m, deterministic)
}
func (m *Folder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Folder.Merge(m, src)
}
func (m *Folder) XXX_Size() int {
	return xxx_messageInfo_Folder.Size(m)
}
func (m *Folder) XXX_DiscardUnknown() {
	xxx_messageInfo_Folder.DiscardUnknown(m)
}

var xxx_messageInfo_Folder proto.InternalMessageInfo

func (m *Folder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Folder) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Folder) GetReadOnly() bool {
	if m != nil {
		return m.ReadOnly
	}
	return false
}

func (m *Folder) GetIgnorePermissions() bool {
	if m != nil {
		return m.IgnorePermissions
	}
	return false
}

func (m *Folder) GetIgnoreDelete() bool {
	if m != nil {
		return m.IgnoreDelete
	}
	return false
}

func (m *Folder) GetDisableTempIndexes() bool {
	if m != nil {
		return m.DisableTempIndexes
	}
	return false
}

func (m *Folder) GetPaused() bool {
	if m != nil {
		return m.Paused
	}
	return false
}

func (m *Folder) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

/**
todo 未使用的部分
 compression certName
 MaxSequence IndexId  Introducer SkipIntroductionRemovals
 使用的字段
 ID name addresses
 */

type Device struct {
	Id                       []byte      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                     string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Addresses                []string    `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Compression              Compression `protobuf:"varint,4,opt,name=compression,proto3,enum=bep.Compression" json:"compression,omitempty"`
	CertName                 string      `protobuf:"bytes,5,opt,name=cert_name,json=certName,proto3" json:"cert_name,omitempty"`
	MaxSequence              int64       `protobuf:"varint,6,opt,name=max_sequence,json=maxSequence,proto3" json:"max_sequence,omitempty"`
	Introducer               bool        `protobuf:"varint,7,opt,name=introducer,proto3" json:"introducer,omitempty"`
	IndexId                  uint64      `protobuf:"varint,8,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	SkipIntroductionRemovals bool        `protobuf:"varint,9,opt,name=skip_introduction_removals,json=skipIntroductionRemovals,proto3" json:"skip_introduction_removals,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}    `json:"-"`
	XXX_unrecognized         []byte      `json:"-"`
	XXX_sizecache            int32       `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{4}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Device) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Device) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Device) GetCompression() Compression {
	if m != nil {
		return m.Compression
	}
	return Compression_METADATA
}

func (m *Device) GetCertName() string {
	if m != nil {
		return m.CertName
	}
	return ""
}

func (m *Device) GetMaxSequence() int64 {
	if m != nil {
		return m.MaxSequence
	}
	return 0
}

func (m *Device) GetIntroducer() bool {
	if m != nil {
		return m.Introducer
	}
	return false
}

func (m *Device) GetIndexId() uint64 {
	if m != nil {
		return m.IndexId
	}
	return 0
}

func (m *Device) GetSkipIntroductionRemovals() bool {
	if m != nil {
		return m.SkipIntroductionRemovals
	}
	return false
}

type Index struct {
	Folder               string      `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	Files                []*FileInfo `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{5}
}

func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetFolder() string {
	if m != nil {
		return m.Folder
	}
	return ""
}

func (m *Index) GetFiles() []*FileInfo {
	if m != nil {
		return m.Files
	}
	return nil
}

type IndexUpdate struct {
	Folder               string      `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	Files                []*FileInfo `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IndexUpdate) Reset()         { *m = IndexUpdate{} }
func (m *IndexUpdate) String() string { return proto.CompactTextString(m) }
func (*IndexUpdate) ProtoMessage()    {}
func (*IndexUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{6}
}

func (m *IndexUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexUpdate.Unmarshal(m, b)
}
func (m *IndexUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexUpdate.Marshal(b, m, deterministic)
}
func (m *IndexUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexUpdate.Merge(m, src)
}
func (m *IndexUpdate) XXX_Size() int {
	return xxx_messageInfo_IndexUpdate.Size(m)
}
func (m *IndexUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_IndexUpdate proto.InternalMessageInfo

func (m *IndexUpdate) GetFolder() string {
	if m != nil {
		return m.Folder
	}
	return ""
}

func (m *IndexUpdate) GetFiles() []*FileInfo {
	if m != nil {
		return m.Files
	}
	return nil
}

type FileInfo struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 FileInfoType `protobuf:"varint,2,opt,name=type,proto3,enum=bep.FileInfoType" json:"type,omitempty"`
	Size                 int64        `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Permissions          uint32       `protobuf:"varint,4,opt,name=permissions,proto3" json:"permissions,omitempty"`
	ModifiedS            int64        `protobuf:"varint,5,opt,name=modified_s,json=modifiedS,proto3" json:"modified_s,omitempty"`
	ModifiedNs           int32        `protobuf:"varint,11,opt,name=modified_ns,json=modifiedNs,proto3" json:"modified_ns,omitempty"`
	ModifiedBy           uint64       `protobuf:"varint,12,opt,name=modified_by,json=modifiedBy,proto3" json:"modified_by,omitempty"`
	Deleted              bool         `protobuf:"varint,6,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Invalid              bool         `protobuf:"varint,7,opt,name=invalid,proto3" json:"invalid,omitempty"`
	NoPermissions        bool         `protobuf:"varint,8,opt,name=no_permissions,json=noPermissions,proto3" json:"no_permissions,omitempty"`
	Version              *Vector      `protobuf:"bytes,9,opt,name=version,proto3" json:"version,omitempty"`
	Sequence             int64        `protobuf:"varint,10,opt,name=sequence,proto3" json:"sequence,omitempty"`
	BlockSize            int32        `protobuf:"varint,13,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	Blocks               []*BlockInfo `protobuf:"bytes,16,rep,name=Blocks,json=blocks,proto3" json:"Blocks,omitempty"`
	SymlinkTarget        string       `protobuf:"bytes,17,opt,name=symlink_target,json=symlinkTarget,proto3" json:"symlink_target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{7}
}

func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (m *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(m, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileInfo) GetType() FileInfoType {
	if m != nil {
		return m.Type
	}
	return FileInfoType_FILE
}

func (m *FileInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileInfo) GetPermissions() uint32 {
	if m != nil {
		return m.Permissions
	}
	return 0
}

func (m *FileInfo) GetModifiedS() int64 {
	if m != nil {
		return m.ModifiedS
	}
	return 0
}

func (m *FileInfo) GetModifiedNs() int32 {
	if m != nil {
		return m.ModifiedNs
	}
	return 0
}

func (m *FileInfo) GetModifiedBy() uint64 {
	if m != nil {
		return m.ModifiedBy
	}
	return 0
}

func (m *FileInfo) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *FileInfo) GetInvalid() bool {
	if m != nil {
		return m.Invalid
	}
	return false
}

func (m *FileInfo) GetNoPermissions() bool {
	if m != nil {
		return m.NoPermissions
	}
	return false
}

func (m *FileInfo) GetVersion() *Vector {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *FileInfo) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *FileInfo) GetBlockSize() int32 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

func (m *FileInfo) GetBlocks() []*BlockInfo {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *FileInfo) GetSymlinkTarget() string {
	if m != nil {
		return m.SymlinkTarget
	}
	return ""
}

type BlockInfo struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Hash                 []byte   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	WeakHash             uint32   `protobuf:"varint,4,opt,name=weak_hash,json=weakHash,proto3" json:"weak_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}


func (m *BlockInfo) Reset()         { *m = BlockInfo{} }
func (m *BlockInfo) String() string { return proto.CompactTextString(m) }
func (*BlockInfo) ProtoMessage()    {}
func (*BlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{8}
}

func (m *BlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockInfo.Unmarshal(m, b)
}
func (m *BlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockInfo.Marshal(b, m, deterministic)
}
func (m *BlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockInfo.Merge(m, src)
}
func (m *BlockInfo) XXX_Size() int {
	return xxx_messageInfo_BlockInfo.Size(m)
}
func (m *BlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BlockInfo proto.InternalMessageInfo

func (m *BlockInfo) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *BlockInfo) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *BlockInfo) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockInfo) GetWeakHash() uint32 {
	if m != nil {
		return m.WeakHash
	}
	return 0
}

type Vector struct {
	Counters             []*Counter `protobuf:"bytes,1,rep,name=counters,proto3" json:"counters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Vector) Reset()         { *m = Vector{} }
func (m *Vector) String() string { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()    {}
func (*Vector) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{9}
}

func (m *Vector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector.Unmarshal(m, b)
}
func (m *Vector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector.Marshal(b, m, deterministic)
}
func (m *Vector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector.Merge(m, src)
}
func (m *Vector) XXX_Size() int {
	return xxx_messageInfo_Vector.Size(m)
}
func (m *Vector) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector.DiscardUnknown(m)
}

var xxx_messageInfo_Vector proto.InternalMessageInfo

func (m *Vector) GetCounters() []*Counter {
	if m != nil {
		return m.Counters
	}
	return nil
}

type Counter struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value                uint64   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Counter) Reset()         { *m = Counter{} }
func (m *Counter) String() string { return proto.CompactTextString(m) }
func (*Counter) ProtoMessage()    {}
func (*Counter) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{10}
}

func (m *Counter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Counter.Unmarshal(m, b)
}
func (m *Counter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Counter.Marshal(b, m, deterministic)
}
func (m *Counter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Counter.Merge(m, src)
}
func (m *Counter) XXX_Size() int {
	return xxx_messageInfo_Counter.Size(m)
}
func (m *Counter) XXX_DiscardUnknown() {
	xxx_messageInfo_Counter.DiscardUnknown(m)
}

var xxx_messageInfo_Counter proto.InternalMessageInfo

func (m *Counter) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Counter) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Request struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Folder               string   `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Offset               int64    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Size                 int32    `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Hash                 []byte   `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	FromTemporary        bool     `protobuf:"varint,7,opt,name=from_temporary,json=fromTemporary,proto3" json:"from_temporary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{11}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetFolder() string {
	if m != nil {
		return m.Folder
	}
	return ""
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Request) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Request) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Request) GetFromTemporary() bool {
	if m != nil {
		return m.FromTemporary
	}
	return false
}

type Response struct {
	Id                   int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []byte    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Code                 ErrorCode `protobuf:"varint,3,opt,name=code,proto3,enum=bep.ErrorCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{12}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_NO_ERROR
}

type DownloadProgress struct {
	Folder               string                        `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	Updates              []*FileDownloadProgressUpdate `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *DownloadProgress) Reset()         { *m = DownloadProgress{} }
func (m *DownloadProgress) String() string { return proto.CompactTextString(m) }
func (*DownloadProgress) ProtoMessage()    {}
func (*DownloadProgress) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{13}
}

func (m *DownloadProgress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadProgress.Unmarshal(m, b)
}
func (m *DownloadProgress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadProgress.Marshal(b, m, deterministic)
}
func (m *DownloadProgress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadProgress.Merge(m, src)
}
func (m *DownloadProgress) XXX_Size() int {
	return xxx_messageInfo_DownloadProgress.Size(m)
}
func (m *DownloadProgress) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadProgress.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadProgress proto.InternalMessageInfo

func (m *DownloadProgress) GetFolder() string {
	if m != nil {
		return m.Folder
	}
	return ""
}

func (m *DownloadProgress) GetUpdates() []*FileDownloadProgressUpdate {
	if m != nil {
		return m.Updates
	}
	return nil
}

type FileDownloadProgressUpdate struct {
	UpdateType           FileDownloadProgressUpdateType `protobuf:"varint,1,opt,name=update_type,json=updateType,proto3,enum=bep.FileDownloadProgressUpdateType" json:"update_type,omitempty"`
	Name                 string                         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              *Vector                        `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	BlockIndexes         []int32                        `protobuf:"varint,4,rep,packed,name=block_indexes,json=blockIndexes,proto3" json:"block_indexes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *FileDownloadProgressUpdate) Reset()         { *m = FileDownloadProgressUpdate{} }
func (m *FileDownloadProgressUpdate) String() string { return proto.CompactTextString(m) }
func (*FileDownloadProgressUpdate) ProtoMessage()    {}
func (*FileDownloadProgressUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{14}
}

func (m *FileDownloadProgressUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileDownloadProgressUpdate.Unmarshal(m, b)
}
func (m *FileDownloadProgressUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileDownloadProgressUpdate.Marshal(b, m, deterministic)
}
func (m *FileDownloadProgressUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileDownloadProgressUpdate.Merge(m, src)
}
func (m *FileDownloadProgressUpdate) XXX_Size() int {
	return xxx_messageInfo_FileDownloadProgressUpdate.Size(m)
}
func (m *FileDownloadProgressUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_FileDownloadProgressUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_FileDownloadProgressUpdate proto.InternalMessageInfo

func (m *FileDownloadProgressUpdate) GetUpdateType() FileDownloadProgressUpdateType {
	if m != nil {
		return m.UpdateType
	}
	return FileDownloadProgressUpdateType_APPEND
}

func (m *FileDownloadProgressUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileDownloadProgressUpdate) GetVersion() *Vector {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *FileDownloadProgressUpdate) GetBlockIndexes() []int32 {
	if m != nil {
		return m.BlockIndexes
	}
	return nil
}

type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{15}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type Close struct {
	Reason               string   `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Close) Reset()         { *m = Close{} }
func (m *Close) String() string { return proto.CompactTextString(m) }
func (*Close) ProtoMessage()    {}
func (*Close) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3f59eb60afbbc6e, []int{16}
}

func (m *Close) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Close.Unmarshal(m, b)
}
func (m *Close) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Close.Marshal(b, m, deterministic)
}
func (m *Close) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Close.Merge(m, src)
}
func (m *Close) XXX_Size() int {
	return xxx_messageInfo_Close.Size(m)
}
func (m *Close) XXX_DiscardUnknown() {
	xxx_messageInfo_Close.DiscardUnknown(m)
}

var xxx_messageInfo_Close proto.InternalMessageInfo

func (m *Close) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterEnum("bep.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("bep.MessageCompression", MessageCompression_name, MessageCompression_value)
	proto.RegisterEnum("bep.Compression", Compression_name, Compression_value)
	proto.RegisterEnum("bep.FileInfoType", FileInfoType_name, FileInfoType_value)
	proto.RegisterEnum("bep.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("bep.FileDownloadProgressUpdateType", FileDownloadProgressUpdateType_name, FileDownloadProgressUpdateType_value)
	proto.RegisterType((*Hello)(nil), "bep.Hello")
	proto.RegisterType((*Header)(nil), "bep.Header")
	proto.RegisterType((*ClusterConfig)(nil), "bep.ClusterConfig")
	proto.RegisterType((*Folder)(nil), "bep.Folder")
	proto.RegisterType((*Device)(nil), "bep.Device")
	proto.RegisterType((*Index)(nil), "bep.Index")
	proto.RegisterType((*IndexUpdate)(nil), "bep.IndexUpdate")
	proto.RegisterType((*FileInfo)(nil), "bep.FileInfo")
	proto.RegisterType((*BlockInfo)(nil), "bep.BlockInfo")
	proto.RegisterType((*Vector)(nil), "bep.Vector")
	proto.RegisterType((*Counter)(nil), "bep.Counter")
	proto.RegisterType((*Request)(nil), "bep.Request")
	proto.RegisterType((*Response)(nil), "bep.Response")
	proto.RegisterType((*DownloadProgress)(nil), "bep.DownloadProgress")
	proto.RegisterType((*FileDownloadProgressUpdate)(nil), "bep.FileDownloadProgressUpdate")
	proto.RegisterType((*Ping)(nil), "bep.Ping")
	proto.RegisterType((*Close)(nil), "bep.Close")
}

func init() { proto.RegisterFile("bep.proto", fileDescriptor_e3f59eb60afbbc6e) }

var fileDescriptor_e3f59eb60afbbc6e = []byte{
	// 1339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcd, 0x72, 0xdb, 0x46,
	0x12, 0x16, 0x08, 0x90, 0x04, 0x9b, 0x3f, 0x05, 0x4d, 0x79, 0x77, 0x61, 0xed, 0xae, 0xad, 0x85,
	0x56, 0xbb, 0x2a, 0x55, 0xc5, 0x49, 0x29, 0xa9, 0x54, 0x5c, 0x95, 0x0b, 0x4d, 0x42, 0x12, 0x1d,
	0x1a, 0x64, 0x86, 0x94, 0x1c, 0xe7, 0x82, 0x02, 0x89, 0xa1, 0x84, 0x12, 0x88, 0x61, 0x30, 0xa0,
	0x6c, 0xe6, 0x9e, 0x7b, 0x1e, 0x24, 0xf7, 0xdc, 0xf3, 0x34, 0x79, 0x8c, 0xd4, 0xf4, 0x00, 0x14,
	0xe4, 0xbf, 0x1c, 0x72, 0x9b, 0xfe, 0xfa, 0x43, 0xa3, 0xe7, 0xeb, 0x1f, 0x00, 0x1a, 0x33, 0xb6,
	0x7a, 0xb2, 0x4a, 0x79, 0xc6, 0x89, 0x3e, 0x63, 0x2b, 0x67, 0x05, 0xd5, 0x73, 0x16, 0xc7, 0x9c,
	0x3c, 0x86, 0x66, 0xc8, 0x6e, 0xa3, 0x39, 0xf3, 0x93, 0x60, 0xc9, 0x6c, 0x6d, 0x5f, 0x3b, 0x6a,
	0x50, 0x50, 0x90, 0x17, 0x2c, 0x99, 0x24, 0xcc, 0xe3, 0x88, 0x25, 0x99, 0x22, 0x54, 0x14, 0x41,
	0x41, 0x48, 0x38, 0x84, 0x4e, 0x4e, 0xb8, 0x65, 0xa9, 0x88, 0x78, 0x62, 0xeb, 0xc8, 0x69, 0x2b,
	0xf4, 0x52, 0x81, 0x4e, 0x04, 0xb5, 0x73, 0x16, 0x84, 0x2c, 0x25, 0xff, 0x05, 0x23, 0xdb, 0xac,
	0xd4, 0xbb, 0x3a, 0x27, 0xd6, 0x13, 0x99, 0xda, 0x0b, 0x26, 0x44, 0x70, 0xc5, 0xa6, 0x9b, 0x15,
	0xa3, 0xe8, 0x25, 0x4f, 0xa1, 0x39, 0xe7, 0xcb, 0x55, 0xca, 0x04, 0xc6, 0xac, 0x20, 0xf9, 0x1f,
	0x65, 0x72, 0xef, 0xce, 0x4d, 0xcb, 0x5c, 0xe7, 0x4b, 0x68, 0xf7, 0xe2, 0xb5, 0xc8, 0x58, 0xda,
	0xe3, 0xc9, 0x22, 0xba, 0x22, 0x87, 0x50, 0x5f, 0xf0, 0x38, 0x64, 0xa9, 0xb0, 0xb5, 0x7d, 0xfd,
	0xa8, 0x79, 0xd2, 0xc4, 0x38, 0xa7, 0x88, 0xd1, 0xc2, 0xe7, 0xfc, 0x5c, 0x81, 0x9a, 0xc2, 0x48,
	0x07, 0x2a, 0x51, 0x98, 0xab, 0x51, 0x89, 0x42, 0xf2, 0x00, 0xaa, 0x71, 0x30, 0x63, 0x71, 0x7e,
	0x7f, 0x65, 0x90, 0x7f, 0x42, 0x23, 0x65, 0x41, 0xe8, 0xf3, 0x24, 0xde, 0xe0, 0xad, 0x4d, 0x6a,
	0x4a, 0x60, 0x94, 0xc4, 0x1b, 0xf2, 0x09, 0x90, 0xe8, 0x2a, 0xe1, 0x29, 0xf3, 0x57, 0x2c, 0x5d,
	0x46, 0x98, 0x9a, 0xb0, 0x0d, 0x64, 0xed, 0x2a, 0xcf, 0xf8, 0xce, 0x41, 0x0e, 0xa0, 0x9d, 0xd3,
	0x43, 0x16, 0xb3, 0x8c, 0xd9, 0x55, 0x64, 0xb6, 0x14, 0xd8, 0x47, 0x8c, 0x7c, 0x06, 0x0f, 0xc2,
	0x48, 0x04, 0xb3, 0x98, 0xf9, 0x19, 0x5b, 0xae, 0xfc, 0x28, 0x09, 0xd9, 0x1b, 0x26, 0xec, 0x1a,
	0x72, 0x49, 0xee, 0x9b, 0xb2, 0xe5, 0x6a, 0xa0, 0x3c, 0xe4, 0xef, 0x50, 0x5b, 0x05, 0x6b, 0xc1,
	0x42, 0xbb, 0x8e, 0x9c, 0xdc, 0x92, 0x92, 0xa8, 0x22, 0x0b, 0xdb, 0x2a, 0x49, 0xd2, 0x47, 0x8c,
	0x16, 0x3e, 0xe7, 0xd7, 0x0a, 0xd4, 0x14, 0x56, 0x92, 0xa4, 0x85, 0x92, 0x10, 0x30, 0x4a, 0x1d,
	0x81, 0x67, 0xf2, 0x2f, 0x68, 0x04, 0x61, 0x28, 0xeb, 0xc0, 0x84, 0xad, 0xef, 0xeb, 0x47, 0x0d,
	0x7a, 0x07, 0x90, 0x93, 0xfb, 0x25, 0x35, 0x4a, 0xf5, 0xff, 0x50, 0x2d, 0xa5, 0xc4, 0x73, 0x96,
	0xe6, 0xcd, 0x57, 0xc5, 0x57, 0x99, 0x12, 0xc0, 0xd6, 0xfb, 0x0f, 0xb4, 0x96, 0xc1, 0x1b, 0x5f,
	0xb0, 0x1f, 0xd6, 0x2c, 0x99, 0x33, 0x94, 0x41, 0xa7, 0xcd, 0x65, 0xf0, 0x66, 0x92, 0x43, 0xe4,
	0x11, 0x40, 0x94, 0x64, 0x29, 0x0f, 0xd7, 0x73, 0x96, 0xe6, 0x1a, 0x94, 0x10, 0xf2, 0x10, 0x4c,
	0x14, 0xd1, 0x8f, 0x42, 0xdb, 0xdc, 0xd7, 0x8e, 0x0c, 0x5a, 0x47, 0x7b, 0x10, 0x92, 0xaf, 0x61,
	0x4f, 0xdc, 0x44, 0x52, 0x64, 0xc5, 0xce, 0x22, 0x9e, 0xf8, 0x29, 0x5b, 0xf2, 0xdb, 0x20, 0x16,
	0x76, 0x03, 0x43, 0xd9, 0x92, 0x31, 0x28, 0x11, 0x68, 0xee, 0x77, 0xfa, 0x50, 0xc5, 0x1a, 0xc8,
	0x0a, 0xa8, 0x06, 0xcb, 0xdb, 0x29, 0xb7, 0xc8, 0x01, 0x54, 0x17, 0x51, 0xcc, 0x84, 0x5d, 0x41,
	0xfd, 0xdb, 0xaa, 0x25, 0xa3, 0x98, 0x0d, 0x92, 0x05, 0xa7, 0xca, 0xe7, 0x3c, 0x87, 0x26, 0x46,
	0xb9, 0x58, 0x85, 0x41, 0xc6, 0xfe, 0x5a, 0xac, 0xdf, 0x75, 0x30, 0x0b, 0x6c, 0x5b, 0x3d, 0xad,
	0x54, 0xbd, 0xc3, 0x7c, 0x30, 0xd5, 0xac, 0xed, 0xde, 0x0b, 0x52, 0x9a, 0x4c, 0x02, 0x86, 0x88,
	0x7e, 0x64, 0xd8, 0xf0, 0x3a, 0xc5, 0x33, 0xd9, 0x87, 0xe6, 0xdb, 0x5d, 0xde, 0xa6, 0x65, 0x88,
	0xfc, 0x1b, 0x60, 0xc9, 0xc3, 0x68, 0x11, 0xb1, 0xd0, 0x17, 0x58, 0x49, 0x9d, 0x36, 0x0a, 0x64,
	0x22, 0xd7, 0xcc, 0xd6, 0x9d, 0x08, 0xbb, 0xb9, 0xaf, 0x1d, 0x55, 0xe9, 0xf6, 0x09, 0x4f, 0xdc,
	0x23, 0xcc, 0x36, 0x76, 0x0b, 0x6b, 0xb5, 0x25, 0x3c, 0xdb, 0x10, 0x5b, 0x76, 0xb4, 0x9c, 0x92,
	0x30, 0x1f, 0x87, 0xc2, 0x94, 0x9e, 0x28, 0xb9, 0x0d, 0xe2, 0xa8, 0x18, 0x82, 0xc2, 0x94, 0xbb,
	0x2b, 0xe1, 0xf7, 0xe6, 0xd3, 0x44, 0x42, 0x3b, 0xe1, 0xe5, 0xd9, 0x3c, 0x84, 0x7a, 0xb1, 0xdb,
	0x64, 0xd9, 0x8b, 0x61, 0xb9, 0x64, 0xf3, 0x8c, 0xa7, 0xb4, 0xf0, 0x91, 0x3d, 0x30, 0xb7, 0xad,
	0x08, 0x78, 0xc1, 0xad, 0x2d, 0xaf, 0x3f, 0x8b, 0xf9, 0xfc, 0xc6, 0x47, 0xe9, 0xda, 0x78, 0xbd,
	0x06, 0x22, 0x13, 0xa9, 0xdf, 0xff, 0xa0, 0xf6, 0x4c, 0x1a, 0xc5, 0x34, 0x76, 0xf0, 0x05, 0x08,
	0x61, 0x09, 0x6b, 0x48, 0x95, 0x99, 0x74, 0xc4, 0x66, 0x19, 0x47, 0xc9, 0x8d, 0x9f, 0x05, 0xe9,
	0x15, 0xcb, 0xec, 0x5d, 0xb5, 0x6c, 0x73, 0x74, 0x8a, 0xa0, 0x73, 0x0d, 0x8d, 0xed, 0xb3, 0xb2,
	0x69, 0xf8, 0x62, 0x21, 0x58, 0x86, 0xc5, 0xd6, 0x69, 0x6e, 0x6d, 0xeb, 0x58, 0xc1, 0x64, 0x54,
	0x1d, 0x09, 0x18, 0xd7, 0x81, 0xb8, 0xc6, 0xda, 0xb6, 0x28, 0x9e, 0xe5, 0x08, 0xbe, 0x66, 0xc1,
	0x8d, 0x8f, 0x0e, 0x55, 0x59, 0x53, 0x02, 0xe7, 0x81, 0xb8, 0x76, 0x4e, 0xa0, 0xa6, 0x64, 0x20,
	0x47, 0x60, 0xce, 0xf9, 0x3a, 0xc9, 0xee, 0xb6, 0x6c, 0x2b, 0x1f, 0x6d, 0x04, 0xe9, 0xd6, 0xeb,
	0x7c, 0x0a, 0xf5, 0x1c, 0x2c, 0x2d, 0x15, 0xa3, 0xd8, 0xb3, 0xb7, 0x41, 0xbc, 0x56, 0x49, 0x19,
	0x54, 0x19, 0xce, 0x2f, 0x1a, 0xd4, 0xa9, 0x54, 0x52, 0x64, 0xa5, 0x27, 0xaa, 0xf8, 0xc4, 0xdd,
	0x48, 0x54, 0xee, 0x8d, 0x44, 0xd1, 0xe0, 0x7a, 0xa9, 0xc1, 0xef, 0x94, 0x30, 0xde, 0xab, 0x44,
	0xf5, 0x3d, 0x4a, 0xd4, 0x4a, 0x4a, 0x1c, 0x42, 0x67, 0x91, 0xf2, 0x25, 0xee, 0x5e, 0x9e, 0x06,
	0xe9, 0x26, 0xef, 0xa7, 0xb6, 0x44, 0xa7, 0x05, 0xe8, 0x50, 0x30, 0x29, 0x13, 0x2b, 0x9e, 0x08,
	0xf6, 0x4e, 0xba, 0x04, 0x8c, 0x30, 0xc8, 0x02, 0x4c, 0xb6, 0x45, 0xf1, 0x4c, 0x1c, 0x30, 0xe6,
	0x3c, 0x54, 0xa9, 0x76, 0xf2, 0xd2, 0xbb, 0x69, 0xca, 0xd3, 0x1e, 0x0f, 0x19, 0x45, 0x9f, 0xc3,
	0xc0, 0xea, 0xf3, 0xd7, 0x49, 0xcc, 0x83, 0x70, 0x9c, 0xf2, 0x2b, 0xb9, 0x1e, 0x3f, 0xb8, 0x0d,
	0x9e, 0x42, 0x7d, 0x8d, 0xfb, 0xa2, 0xd8, 0x07, 0x8f, 0xb7, 0xa3, 0xfc, 0x76, 0x0c, 0xb5, 0x57,
	0x68, 0xc1, 0x77, 0x7e, 0xd3, 0x60, 0xef, 0xc3, 0x3c, 0xd2, 0x87, 0xa6, 0x62, 0xfa, 0xa5, 0x2f,
	0xf8, 0xc1, 0x9f, 0x44, 0xc7, 0xd5, 0x01, 0xeb, 0xed, 0xf9, 0xbd, 0x5f, 0x8e, 0xd2, 0x88, 0xe9,
	0x1f, 0x19, 0xb1, 0x03, 0x68, 0xab, 0x31, 0x2a, 0xbe, 0x7c, 0xc6, 0xbe, 0x7e, 0x54, 0xa5, 0xad,
	0x99, 0xea, 0x76, 0xc4, 0x9c, 0x1a, 0x18, 0xe3, 0x28, 0xb9, 0x72, 0x1e, 0x43, 0xb5, 0x17, 0x73,
	0x81, 0x75, 0x4f, 0x59, 0x20, 0x78, 0x52, 0x08, 0xa5, 0xac, 0xe3, 0x9f, 0x34, 0x68, 0x96, 0xfe,
	0x3c, 0x08, 0x81, 0x4e, 0x6f, 0x78, 0x31, 0x99, 0xba, 0xd4, 0xef, 0x8d, 0xbc, 0xd3, 0xc1, 0x99,
	0xb5, 0x43, 0x1a, 0x50, 0x1d, 0x78, 0x7d, 0xf7, 0x3b, 0x4b, 0x23, 0x16, 0xb4, 0xf0, 0xe8, 0x5f,
	0x8c, 0xfb, 0xdd, 0xa9, 0x6b, 0x55, 0x48, 0x13, 0xea, 0xd4, 0xfd, 0xf6, 0xc2, 0x9d, 0x4c, 0x2d,
	0x9d, 0xb4, 0xc0, 0xa4, 0xee, 0x64, 0x3c, 0xf2, 0x26, 0xae, 0x65, 0x90, 0xbf, 0xc1, 0x6e, 0x7f,
	0xf4, 0xd2, 0x1b, 0x8e, 0xba, 0x7d, 0x7f, 0x4c, 0x47, 0x67, 0xd4, 0x9d, 0x4c, 0xac, 0x2a, 0x31,
	0xc1, 0x18, 0x0f, 0xbc, 0x33, 0xab, 0x26, 0x03, 0xf7, 0x86, 0xa3, 0x89, 0x6b, 0xd5, 0x8f, 0xff,
	0x0f, 0xe4, 0xdd, 0x7f, 0x1a, 0x49, 0xf5, 0x46, 0x9e, 0x6b, 0xed, 0x90, 0x3a, 0xe8, 0xc3, 0xef,
	0xbf, 0xb0, 0xb4, 0xe3, 0x13, 0x68, 0x96, 0x19, 0x2d, 0x30, 0x5f, 0xb8, 0xd3, 0x6e, 0xbf, 0x3b,
	0xed, 0xaa, 0x4c, 0x3d, 0xf7, 0xd2, 0xa5, 0x96, 0x46, 0x00, 0x6a, 0xdd, 0xe1, 0xcb, 0xee, 0xab,
	0x89, 0x55, 0x39, 0x66, 0xd0, 0x2a, 0x2f, 0x71, 0x19, 0xf6, 0x74, 0x30, 0x94, 0x61, 0xdb, 0xd0,
	0xe8, 0x0f, 0xa8, 0xdb, 0x9b, 0x8e, 0xe8, 0x2b, 0x4b, 0x23, 0x0f, 0xa0, 0x35, 0x79, 0xf5, 0x62,
	0x38, 0xf0, 0xbe, 0xf1, 0x91, 0x50, 0xd9, 0xab, 0x98, 0x1a, 0x79, 0x08, 0xbb, 0x05, 0x7a, 0x47,
	0xd6, 0xd1, 0xd5, 0x84, 0x7a, 0xee, 0xb2, 0x8c, 0xe3, 0xe7, 0xd0, 0xd8, 0xf6, 0xac, 0x4c, 0xcc,
	0x1b, 0xf9, 0x2e, 0xa5, 0x23, 0x6a, 0xed, 0x48, 0xde, 0x99, 0xeb, 0xb9, 0x74, 0xd0, 0x53, 0x22,
	0x7a, 0x23, 0x7f, 0x72, 0xd1, 0x3b, 0xcf, 0xdf, 0xa2, 0x64, 0xbd, 0xec, 0x0e, 0x07, 0x7d, 0x85,
	0xe8, 0xc7, 0x5f, 0xc1, 0xa3, 0x8f, 0xb7, 0x13, 0x5e, 0x70, 0x3c, 0x76, 0xbd, 0xbe, 0xb5, 0x23,
	0xcf, 0xa7, 0x23, 0x7a, 0xe6, 0x4e, 0x2d, 0x6d, 0x56, 0xc3, 0x7f, 0xdc, 0xcf, 0xff, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xe6, 0xb5, 0x3d, 0x4d, 0xf0, 0x0a, 0x00, 0x00,
}
